project: unloan/changesets-action

# Additional repositories related to your project
repos:
- unloan/changesets-action

# Files and folders to send to TAC for review
include:
- README.md

# Can be also be a glob pattern, example:
# - docs/**
